[build-system]
requires = ["setuptools", "music21>=7.3"]
build-backend = "setuptools.build_meta"

[project]
name = "trop"
authors = [
    {name = "Jawor Iwanow"},
]
readme = "README.md"
dynamic = ["v0.1", "package for the transcription of byzantine notation"]
